name: flutter_application_1
description: "Aplikasi Rental PlayStation Profesional"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # HANYA ASSET YANG WAJIB ADA
  assets:
    - assets/loading_ps.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#CDF6FF"